# Generated by Django 3.1.5 on 2021-01-17 08:03

from django.db import migrations, models
import django.db.models.deletion
import stadiums.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='StadiumSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_code', models.PositiveIntegerField()),
                ('view', models.ImageField(blank=True, null=True, upload_to=stadiums.models.stadium_view_dir_path)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadiums.stadium')),
            ],
            options={
                'unique_together': {('stadium', 'seat_code')},
            },
        ),
    ]
