# Generated by Django 3.1.5 on 2021-01-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiumseat',
            name='seat_column',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stadiumseat',
            name='seat_row',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stadiumseat',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='stadiums.stadium'),
        ),
        migrations.AlterUniqueTogether(
            name='stadiumseat',
            unique_together={('seat_row', 'seat_column'), ('stadium', 'seat_code')},
        ),
    ]
