# Generated by Django 3.1.5 on 2021-01-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0002_auto_20210117_1526'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stadiumseat',
            unique_together={('stadium', 'seat_code')},
        ),
        migrations.RemoveField(
            model_name='stadiumseat',
            name='seat_column',
        ),
        migrations.RemoveField(
            model_name='stadiumseat',
            name='seat_row',
        ),
    ]
