# Generated by Django 3.1.5 on 2021-01-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0004_auto_20210117_1527'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stadiumseat',
            unique_together={('seat_row', 'seat_column'), ('stadium_id', 'seat_code')},
        ),
    ]
