# Generated by Django 3.1.5 on 2021-01-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0005_auto_20210117_1540'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stadiumseat',
            unique_together={('stadium', 'seat_code'), ('seat_row', 'seat_column')},
        ),
    ]
