# Generated by Django 3.1.5 on 2021-01-17 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0007_auto_20210117_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='row_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stadium',
            name='seat_in_row',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='stadiumseat',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='StadiumSeatRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(default=1)),
                ('seat_count', models.PositiveIntegerField(default=1)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='stadiums.stadium')),
            ],
        ),
        migrations.RemoveField(
            model_name='stadiumseat',
            name='seat_column',
        ),
        migrations.RemoveField(
            model_name='stadiumseat',
            name='seat_row',
        ),
    ]
