# Generated by Django 3.1.5 on 2021-01-17 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0008_auto_20210117_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiumseat',
            name='row',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='stadiums.stadiumseatrow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadiumseat',
            name='seat_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='stadiumseat',
            unique_together={('seat_number', 'seat_number', 'stadium')},
        ),
    ]
