# Generated by Django 3.1.5 on 2021-01-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0009_auto_20210117_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium',
            name='capacity',
        ),
    ]
