# Generated by Django 3.1.5 on 2021-01-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0010_remove_stadium_capacity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stadiumseat',
            unique_together={('row', 'seat_number', 'stadium')},
        ),
    ]
