# Generated by Django 3.1.5 on 2021-01-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0011_auto_20210117_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StadiumSeat',
        ),
    ]
