# Generated by Django 3.1.5 on 2021-01-17 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stadiums', '0011_auto_20210117_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=80)),
                ('team_b', models.CharField(max_length=80)),
                ('start_time', models.DateTimeField()),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='stadiums.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='MatchSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(default=1)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='matches.match')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadiums.stadiumseatrow')),
            ],
            options={
                'unique_together': {('row', 'seat_number', 'match')},
            },
        ),
    ]
