# Generated by Django 3.1.5 on 2021-01-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchseat',
            name='price',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
